@MultiWeather_HostAddress = http://localhost:5295

GET {{MultiWeather_HostAddress}}/MultiWeather/SearchLocation
Accept: application/json

###

GET {{MultiWeather_HostAddress}}/MultiWeather/GetCurrent
Accept: application/json

###
